### ISSUE TITLE
torch.load() issue

### ISSUE THREAD

**Issue by ijzepeda** [thoppe/instafilter#2]
It seems that for devices with only CPU is failing to load the model.
on filtering.py at line 34:
` state = torch.load(f_model)`
it is required the device parameter
 `state = torch.load(f_model, map_location=torch.device(device))`

**Comment by thoppe** [comment]
Hi Ivan, thanks for taking a look. Submit a PR and I'd be happy to merge it
in!

**Comment by pryadchenko** [comment]
It seems to be not done yet. I fall into the same Issue. Could you please fix it?

**Comment by thoppe** [comment]
Submit a PR and I'll merge it in. I'm not actively.workikg on this right
now.

**Comment by duc12111** [comment]
Hi Thoppe, 
Can you release this new version (0.3.2)? With this feature? It would be more convenient for me to install with pip. 
Thank you in advance.

**Comment by thoppe** [comment]
It has been updated: https://pypi.org/project/instafilter/0.3.2/
```pip install instafilter -U```
